services:
  - type: web
    name: south-asian-history-research
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SEARCH_API_KEY
        sync: false
      - key: PYTHONPATH
        value: .
    plan: starter